version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: excel
      DB_NAME: user-management-db
      JWT_SECRET: VSLVjYxiJqHtdPdMECh82jTCfgAHonN2AR1dXUkpEMg=
      PORT: 3000
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: excel
      POSTGRES_DB: user-management-db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
